spring:
  application:
    name: "inoptra-shopping-cart-application"
  profiles:
    active: local-h2

server:
  port: 8085

management.endpoints:
    web.base-path: /actuator
    health.show-details: always